# CI/CD Template for Lambda Function Repositories
#
# This template provides a standard CI/CD pipeline for Lambda-based applications.
# It includes build, test, contract validation, and deployment steps.
#
# Usage: Create new workflow in your repo from Actions > New workflow > Lambda CI

name: Lambda CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # Lint and type check
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run type-check || npm run build

  # Run unit tests
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage

      - name: Upload coverage
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  # Build the Lambda package
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: dist/

  # Contract validation (PROC-007)
  contract-validation:
    name: Contract Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    uses: teric-io/.github/.github/workflows/contract-validation.yml@main
    with:
      advisory_only: false
    secrets: inherit

  # Deploy to Lambda (main branch only)
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          FUNCTION_NAME="${{ github.event.repository.name }}"

          # Create deployment package
          cd dist
          zip -r ../lambda.zip .
          cd ..

          # Update Lambda function
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://lambda.zip \
            --publish

          echo "Deployed to Lambda: $FUNCTION_NAME"
